services:
  fastapi:
    build: .
    container_name: testing_app
    restart: always
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_HOST}
      - AWS_REGION_NAME=${AWS_REGION_NAME}
      - AWS_COGNITO_APP_CLIENT_ID=${AWS_COGNITO_APP_CLIENT_ID}
      - AWS_COGNITO_APP_CLIENT_SECRET=${AWS_COGNITO_APP_CLIENT_SECRET}
      - AWS_COGNITO_USER_POOL_ID=${AWS_COGNITO_USER_POOL_ID}

    networks:
      - network

  postgres:
    image: postgres:14
    ports:
      - 5433:5432
    volumes:
      - ./postgres-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_HOST}
    networks:
      - network
networks:
  network:
    driver: bridge
    name: test_network
